### ISSUE TITLE
I've been wondering

### ISSUE THREAD

**Issue by memoowi** [numen111104/nide_tix_backend#3]
It was Laravel right? then how tf did the `Languages` section on the side of the github repo pages show that it was `Javascript` at the most 🤔💭

**Comment by numen111104** [comment]
So basically, I use Laravel for backend development. When you check the Blade section, you'll find scripts in almost every Blade file. I rely on AJAX for asynchronous requests more than traditional PHP form submissions. Therefore, JavaScript is likely the primary language in my development stack. And actually, there's a lot of JavaScript in this because I'm using a template. I only add a little JavaScript to trigger an alert for the delete action.

**Comment by memoowi** [comment]
makes sense
